// Placeholder graph shipped for a fresh clone.
// Real graphs are generated by build.py from docs/*.md, connectors.json and
// tools.json — run `py -3 build.py` to replace this with your own galaxy.
const GRAPH = {
  "nodes": [
    {
      "id": 0,
      "label": "MoAI — the project",
      "type": "project",
      "group": "project",
      "excerpt": "MoAI is a local, voice-enabled second brain. Notes, connectors, and tools become a navigable 3D knowledge galaxy — ask questions by voice or text, save new notes on the fly, and fly the camera to the source of every answer. Everything runs on your machine except the question sent to the Anthropic API and the Three.js / 3d-force-graph bundle loaded from esm.sh.\n\n```mermaid\ngraph TD\n  Docs[\"docs/*.md\"] --> Build[\"build.py\"]\n  Connectors[\"connectors.json / tools.json\"] --> Build\n  Build --> Data[\"viewer/graph-data.js\"]\n  Data --> Viewer[\"viewer/index.html\"]\n  Viewer <--> Server[\"server.py\"]\n  Server --> API[\"Anthropic API\"]\n```\n\nThis is a placeholder node. Clone the repo, copy config.example.json to config.json with your own Anthropic key, add your own notes under docs/, then run build.py to grow your own galaxy.",
      "path": "docs/projects/example-project-moai-galaxy.md",
      "val": 1
    }
  ],
  "links": [],
  "mtime": 1785715532
};
